### ISSUE TITLE
evaluate alternatives to RT for support

### ISSUE THREAD

**Issue by mbjones** [NCEAS/arctic-data-center#8]
RT has stood us well for interactions with PIs without requiring github accounts for them.  But, it is somewhat clunky, and doesn't integrate into our broader development workflows with tickets in GitHub repositories.  Consider migrating to an alternative system that integrates better with our dev workflow. Let's generate a list to consider and evaluate here, including:

- [FreshDesk](https://arcticdatacenter.freshdesk.com)
- [GitLab Service Desk](https://gitlab.com/help/user/project/service_desk)
- ...

**Comment by jagoldstein** [comment]
We evaluated FreshDesk 2 months ago during our free trial period. We ruled it out due to a lack of desired ticketing features and its proprietary nature ($49/agent/month).

The ADC support team elected to stick with RT but incorporate improvements such as listing and updating processing "to-do" tasks under "Custom Field" which displays at the top of each ticket, removing superfluous and confusing fields, and assigning priority values to tickets as necessary.

**Comment by jagoldstein** [comment]
GitLab is geared towards the private sector. The GitLab ticketing feature is called "Service Desk" and requires at least a Silver or Premium plan subscription for $19/user/month. "Customers" (known as "requestors" in RT), are users too and GitLab charges for each one, each month.
BUT, may be a free option for educational institutions, like UCSB!

GitHub requires that all users have a GitHub account, so that wouldn't work either.

"It's déjà vu all over again."

**Comment by amoeba** [comment]
That's not quite the take I got @jagoldstein. 

> "GitLab is geared towards the private sector."

This is kinda news to me. Is there something you saw/read that indicated that?

> "requires at least a Silver or Premium plan subscription for $19/user/month"

According to https://about.gitlab.com/2018/06/05/gitlab-ultimate-and-gold-free-for-education-and-open-source/, as both an education org and an open source and non-profit org, we'd apply for the higher tiers for free.

> "Customers" (known as "requestors" in RT), are users too and GitLab charges for each one, each month."

I read the docs the opposite way. From https://docs.gitlab.com/ee/user/project/service_desk.html#how-it-works:

> GitLab Service Desk is a simple way to allow people to create issues in your GitLab instance without needing their own user account.

**Comment by mbjones** [comment]
Yeah, I think we need to look more deeply. I brought it up because my interpretation matches Bryce's.  I think GitLab Service Desk is a hybrid of features of GitHub (nice UI, code repo integration), Waffle (decent board planning, but not as nice as waffle itself), and RT (email support for external users).  And I think we  would qualify for the free educational account with all features at Gold/Ultimate levels.

**Comment by jagoldstein** [comment]
@amoeba , yes I read the following in the "User Documentation" available at https://docs.gitlab.com/ee/user/project/service_desk.html:

> "Here's how Service Desk will work for you:

> You'll provide a project-specific email address to your paying customers, who can email you directly from within the app"

This GitLab documentation indicates that "customers" pay. Elsewhere on the GitLab site, I read that they can charge at the end of the month and bill the account holder (us) directly for each user.

But if we qualify for free educational use due to our UCSB affiliation, then this is not a concern! I agree that we likely do qualify for this designation.

I've contacted GitLab with these questions and am awaiting their reply. (The contact form was clunky, which concerned me.)

**Comment by amoeba** [comment]
Ah. I was thinking you were talking about GitLab as a whole. Service Desk is just a minor feature within GitLab's entire stack, which provides everything GitHub provides and a lot more. The quote you pulled from the Service Desk docs is a bit private-y, I agree. After all this, I feel a bit unclear as to how it all works so I'm looking forward to seeing it in action.

**Comment by amoeba** [comment]
Hey @mbjones & @jesse I was playing around with GitLab Service Desk and one feature I see it doesn't have is the ability to add notes/comments to tickets without emailing the respondent. Renaming or changing labels doesn't trigger an email. I also can't see a way to send emails out to more than one respondent (the original respondent).

These are things we've been making use of with RT so maybe Service Desk isn't all puppies and kittens.

**Comment by mbjones** [comment]
Good points.
